language: node_js
node_js:
  - "stable"
script:
 - npm run build
 - echo "Beam me up, Scotty"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project carlosanjos-dev --token $FIREBASE_TOKEN
env:
  - VUE_APP_GA=$VUE_APP_GA